# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 20:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ImageMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_feedback', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=50)),
                ('caption', models.CharField(max_length=144)),
                ('image', models.ImageField(upload_to='static/mp_images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('artform', models.CharField(choices=[('PAINT', 'paint'), ('DRAW', 'draw'), ('SCULPTURE', 'sculpture'), ('PHOTO', 'photo'), ('MIXED', 'mixed media'), ('DIGITAL', 'digital')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ImageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('image', models.ManyToManyField(to='mp_app.ImageMP')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('has_seen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TextFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=20)),
                ('has_seen', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TextMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_feedback', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('artform', models.CharField(choices=[('POETRY', 'poetry'), ('SHORT STORY', 'short story'), ('HUMOR', 'humor'), ('ASCII', 'ascii')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TextTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('text', models.ManyToManyField(to='mp_app.TextMP')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='static/user_images/')),
                ('bio', models.CharField(max_length=500)),
                ('fb_link', models.URLField()),
                ('insta_link', models.URLField()),
                ('twitter_link', models.URLField()),
                ('dob', models.DateField()),
                ('allow_messages', models.BooleanField(default=False)),
                ('followers', models.ManyToManyField(to='mp_app.UserProfile')),
                ('messages', models.ManyToManyField(to='mp_app.Messages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='textmp',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_app.UserProfile'),
        ),
        migrations.AddField(
            model_name='textfeedback',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_app.UserProfile'),
        ),
        migrations.AddField(
            model_name='textfeedback',
            name='masterpeace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_app.TextMP'),
        ),
        migrations.AddField(
            model_name='imagemp',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_app.UserProfile'),
        ),
        migrations.AddField(
            model_name='imagefeedback',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_app.UserProfile'),
        ),
        migrations.AddField(
            model_name='imagefeedback',
            name='masterpeace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_app.ImageMP'),
        ),
    ]
