# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 16:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mp_app', '0002_auto_20170423_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message_text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='has_seen',
            new_name='read',
        ),
        migrations.RenameField(
            model_name='textfeedback',
            old_name='has_seen',
            new_name='read',
        ),
        migrations.RemoveField(
            model_name='imagefeedback',
            name='author',
        ),
        migrations.RemoveField(
            model_name='imagetag',
            name='image',
        ),
        migrations.RemoveField(
            model_name='textfeedback',
            name='author',
        ),
        migrations.RemoveField(
            model_name='texttag',
            name='text',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='messages',
        ),
        migrations.AddField(
            model_name='imagefeedback',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagefeedback',
            name='critic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagefeedback',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagemp',
            name='tag',
            field=models.ManyToManyField(to='mp_app.ImageTag'),
        ),
        migrations.AddField(
            model_name='message',
            name='from_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_from_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='to_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textfeedback',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textfeedback',
            name='critic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textmp',
            name='tag',
            field=models.ManyToManyField(to='mp_app.TextTag'),
        ),
        migrations.AlterField(
            model_name='imagefeedback',
            name='icon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_app.FeedbackType'),
        ),
        migrations.AlterField(
            model_name='imagemp',
            name='artform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_app.Artform'),
        ),
        migrations.AlterField(
            model_name='imagemp',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='textfeedback',
            name='icon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_app.FeedbackType'),
        ),
        migrations.AlterField(
            model_name='textmp',
            name='artform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_app.Artform'),
        ),
        migrations.AlterField(
            model_name='textmp',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
