# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0003_auto_20170424_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fb_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, to='mp_app.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='insta_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitter_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
