# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0005_auto_20170424_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefeedback',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mp_app.FeedbackType'),
        ),
        migrations.AlterField(
            model_name='textfeedback',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mp_app.FeedbackType'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='mp_app/static/user_images/'),
        ),
    ]
