# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0006_auto_20170424_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='masterpeace/static/user_images/'),
        ),
    ]
