# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0008_auto_20170425_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemp',
            name='image',
            field=models.ImageField(upload_to='masterpeace/static/mp_images/'),
        ),
    ]
