# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0009_auto_20170426_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemp',
            name='image',
            field=models.FileField(upload_to='masterpeace/static/mp_images/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='masterpeace/static/user_images/'),
        ),
    ]
