# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0009_auto_20170426_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemp',
            name='image',
            field=models.ImageField(upload_to='mp_images/'),
        ),
    ]
