# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0010_auto_20170429_1821'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='imagemp',
        #     name='feedback1',
        #     field=models.IntegerField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='imagemp',
        #     name='feedback2',
        #     field=models.IntegerField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='imagemp',
        #     name='feedback3',
        #     field=models.IntegerField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='imagemp',
        #     name='feedback4',
        #     field=models.IntegerField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='imagemp',
        #     name='feedback5',
        #     field=models.IntegerField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='textmp',
        #     name='feedback1',
        #     field=models.IntegerField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='textmp',
        #     name='feedback2',
        #     field=models.IntegerField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='textmp',
        #     name='feedback3',
        #     field=models.IntegerField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='textmp',
        #     name='feedback4',
        #     field=models.IntegerField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='textmp',
        #     name='feedback5',
        #     field=models.IntegerField(null=True),
        # ),
    ]
