# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0010_auto_20170502_1916'),
        ('mp_app', '0011_auto_20170503_2001'),
    ]

    operations = [
    ]
