# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0012_merge_20170504_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemp',
            name='caption',
            field=models.CharField(blank=True, max_length=144, null=True),
        ),
        migrations.AlterField(
            model_name='textmp',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
