# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0013_auto_20170504_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pic',
            field=models.TextField(default='none'),
        ),
    ]
