# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0016_auto_20170505_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemp',
            name='image',
            field=models.TextField(default='none', max_length=10000000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pic',
            field=models.TextField(default='none', max_length=100000000),
        ),
    ]
