# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0011_auto_20170504_2020'),
        ('mp_app', '0017_auto_20170505_1846'),
    ]

    operations = [
    ]
