# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0018_auto_20170506_1820'),
        ('mp_app', '0011_auto_20170504_2020'),
    ]

    operations = [
    ]
