# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 03:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0019_auto_20170506_2010'),
        ('mp_app', '0018_auto_20170506_2337'),
        ('mp_app', '0019_merge_20170506_2015'),
    ]

    operations = [
    ]
