# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0020_merge_20170507_0319'),
        ('mp_app', '0020_auto_20170506_2025'),
    ]

    operations = [
    ]
